Feature/pb 466 status oppdatering
navikt/dittnav-event-aggregator pull request #115
Opened 2020-08-19 06:42 UTC by VanessaKjK

Har lagt til en ny brukernotifikasjonstype StatusOppdatering.

2020-08-19 09:05 UTC, greger-nl requested changes
Dette ser bra ut, men jeg har et par kommentarer.

Vi må ha på plass integrasjonstester for den nye eventtypen før denne PR-en kan godkjennes.

2020-08-19 09:05 UTC, greger-nl commented on src/main/resources/db/migration/V1.1.6__Ny_tabell_statusoppdatering.sql
> +ALTER TABLE statusoppdatering ADD CONSTRAINT statusOppdateringsEventErUnikMedIdOgProdusent UNIQUE (eventid, systembruker);
Kan du legge til indekser for tabellen også? På samme måte som ble gjort rett før sommerferien for de andre tabellene 😉

2020-09-10 12:53 UTC, Robert-Larsen approved these changes
Synes dette ser bra ut nå 👍

2020-09-11 07:48 UTC, greger-nl approved these changes

2020-09-11 08:27 UTC, merged